blank_issues_enabled: false
contact_links:
  - name: 常见问题解答
    url: https://github.com/liuzq2002/Adguard-Home-For-Magisk-Mod#faq
    about: 请先查阅已知问题解决方案
  - name: 实时讨论 
    url: https://qm.qq.com/q/kKit0PhHOM
    about: 加入 春梦闲聊&交流群
    
